export const extensionName = "st-immersive-sound";
export const extensionFolderPath = `scripts/extensions/third-party/st-immersive-sound`;

export const defaultSettings = {
    enable_plugin: false,
    highlightColor: '#FFC800',
    highlightOpacity: 0.4,
    textColor: '#FF0000',
    readingSpeed: 450,
    musicStartsWithParagraph: true,
    seamlessMusic: true,
    enable3dAudio_music: false,
    enable3dAudio_ambiance: false,
    enable3dAudio_sfx: false,
    musicFadeIn: 3,
    musicFadeOut: 2,
    ambianceFadeIn: 3,
    ambianceFadeOut: 2,
    sfxFadeIn: 0.1,
    sfxFadeOut: 0.1,
    masterVolume: 0.5,
    musicVolume: 0.2,
    ambianceVolume: 0.6,
    sfxVolume: 1,
    music_refDistance: 0.6,
    music_maxDistance: 20,
    music_rolloffFactor: 0.3,
    music_posX: 0,
    music_posY: 0,
    music_posZ: 2.5,
    ambiance_refDistance: 0.6,
    ambiance_maxDistance: 20,
    ambiance_rolloffFactor: 0.3,
    ambiance_posX: 0,
    ambiance_posY: 0,
    ambiance_posZ: 2.4,
    sfx_refDistance: 0.6,
    sfx_maxDistance: 20,
    sfx_rolloffFactor: 0.3,
    sfx_posX: 0,
    sfx_posY: 0,
    sfx_posZ: 2,
    enable3dAudio_sfx_wait: false,
    sfx_waitFadeIn: 0.1,
    sfx_waitFadeOut: 0.1,
    sfx_waitVolume: 1,
    sfx_wait_refDistance: 0.6,
    sfx_wait_maxDistance: 20,
    sfx_wait_rolloffFactor: 0.3,
    sfx_wait_posX: 0,
    sfx_wait_posY: 0,
    sfx_wait_posZ: 2,
};
