export const extensionName = "st-immersive-sound";
export const extensionFolderPath = `scripts/extensions/third-party/st-immersive-sound`;

export const defaultSettings = {
   "autoPlay": true,
    "enable_plugin": true,
    "readingSpeed": 650,
    "highlightColor": "#FFC800",
    "textColor": "#d71d1d",
    "highlightOpacity": 0.4,
    "musicStartsWithParagraph": true,
    "seamlessMusic": true,
    "regexReplace": false,
    "masterVolume": 1.44,
    "musicVolume": 0.08,
    "ambianceVolume": 0.61,
    "sfxVolume": 0.23,
    "sfx_waitVolume": 1,
    "musicFadeIn": 1,
    "musicFadeOut": 1,
    "ambianceFadeIn": 1,
    "ambianceFadeOut": 1,
    "sfxFadeIn": 0.1,
    "sfxFadeOut": 0.1,
    "sfx_waitFadeIn": 0.1,
    "sfx_waitFadeOut": 0.1,
    "enable3dAudio_music": true,
    "enable3dAudio_ambiance": true,
    "enable3dAudio_sfx": true,
    "enable3dAudio_sfx_wait": false,
    "music_refDistance": 0.6,
    "music_maxDistance": 20,
    "music_rolloffFactor": 0.3,
    "music_posX": 0,
    "music_posY": 0,
    "music_posZ": 1,
    "ambiance_refDistance": 0.6,
    "ambiance_maxDistance": 20,
    "ambiance_rolloffFactor": 0.3,
    "ambiance_posX": 0,
    "ambiance_posY": 0,
    "ambiance_posZ": 4,
    "sfx_refDistance": 0.6,
    "sfx_maxDistance": 20,
    "sfx_rolloffFactor": 0.3,
    "sfx_posX": 0,
    "sfx_posY": 0,
    "sfx_posZ": 1.7,
    "sfx_wait_refDistance": 0.6,
    "sfx_wait_maxDistance": 20,
    "sfx_wait_rolloffFactor": 0.3,
    "sfx_wait_posX": 0,
    "sfx_wait_posY": 0,
    "sfx_wait_posZ": 0,
    "enable_vibration": true,
    "autoVibrationLowThreshold": 20,
    "autoVibrationLowDuration": 50,
    "autoVibrationHighThreshold": 20,
    "autoVibrationHighDuration": 50,
    "vibration_profiles": {
        "默认": [
            0,
            100,
            50,
            100,
            50
        ]
    },
    "current_vibration_profile": "默认",
    "enable_float_ball": true,
    "float_ball_bg_color": "#ADD8E6",
    "float_ball_icon_color": "#FFFFFF",
    "float_ball_opacity": 1,
    "float_ball_size": 34,
    "voiceVolume": 1,
    "voiceFadeIn": 0.1,
    "voiceFadeOut": 0.1,
    "enable3dAudio_voice": true,
    "voice_refDistance": 0.6,
    "voice_maxDistance": 20,
    "voice_rolloffFactor": 0.3,
    "voice_posX": 0,
    "voice_posY": 0,
    "voice_posZ": 1.9
};
